- name: install fail2ban
  hosts: web
  become: yes    #root user -b
  tasks:
    - name: install fail2ban
      ansible.builtin.dnf:
        name: fail2ban
        state: latest #new version
    - name: start fail2ban
      ansible.builtin.service: #service means starting
        name: fail2ban
        state: started
        enabled: yes