- name: variables
  hosts: localhost
  vars: #variables declaration (vars nee chupithudi)
    course: "devops"
    trainer: "venkat"
    duration: "120hours"
  tasks: 
    - name: print information
      ansible.builtin.debug:
        msg: "hi we are learning {{course}} from trainer {{trainer}} total duration is {{duration}}"