- name: variable preference
  hosts: localhost
    vars:
    inventation: "today my birthday variable"
  vars_files:
  - vars.yaml
    vars_prompt:
     - name: inventation
      prompt: "please enter wishes"
      private: false
  tasks:
  - name: check preference
      vars:
        inventation: "today my birthday task variable"
    ansible.builtin.bebug:
      msg: "hello , {{inventation}}"