- name: demo on loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "hello {{item}}"
    loop:
    - AWS
    - terraform
    - ansible        #confuse what is items 
    - devops
 