- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loops:
    - gcc
    - postfix
    - fail2ban
    - docker  